[api]
pre_url=http://bfc-solitaire-ios.luckfun.vip

#[db]
#host=luckyday-cluster.cluster-cpvmsbtagw1g.us-west-1.rds.amazonaws.com
#port=3306
#user=luckyday
#
#pwd=rpwd123456


[data]

common_data={"bundle_id": "com.game.solitairethrill","carrier_name": "\u65e0\u8fd0\u8425\u5546","client_version": "18","country_code": "CN","system_language": "zh-Hans-CN","time_zone": "Asia/Shanghai","udid": "49C59AD0-457B-4CF0-9429-9C3CB3A91278","version": "44","timestamp": ""}
guest_data={"address": "China;Sichuan","appsflyer_id": "1770188407693-3080160","device_info": "iPhone 7(15.2)","idfa": "7C40B7D4-5F8C-49C8-9E08-79E6B63B2211","install_vx": "0","install_zfb": "0"}




#channel_data = {"gps": "","gps_address": "30.554642,104.057272","country": "CN","state": "Sichuan"}
#createdata = {"session_id": "","gps": "30.5545174,104.0570734","gps_address": "","client_pay_type": "credit_card","charge_id": ""}

[log]
file_handler=WARNING
console_handler=INFO

